---
- name: patch AWX deployment to support LDAPS
  k8s:
    state: present
    definition: "{{ lookup('template', 'deployment-awx.yml.j2') }}"

- include: wait-for-awx.yml

- name: "Update Ansible Tower LDAP config"
  uri:
    url: "https://{{ awx_kubernetes_ingress_hostname }}/api/v2/settings/ldap/"
    user: "{{ awx_admin_user }}"
    password: "{{ awx_admin_password }}"
    force_basic_auth: yes
    method: PUT
    body: "{{ lookup('template', 'ldap.json.j2') }}"
    body_format: 'json'
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    validate_certs: no
