---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: awx
    box: centos/7
    cpus: 4
    memory: 6144
    interfaces:
      - auto_config: true
        ip: 172.28.128.3
        network_name: private_network
        type: static
provisioner:
  name: ansible
  log: true
  inventory:
    host_vars:
      awx:
        rke_nodes:
          - address: 172.28.128.3
            user: vagrant
            role: [controlplane, etcd, worker]
verifier:
  name: testinfra
  lint:
    name: flake8
